### ISSUE TITLE
Cafeteria-1 학식 보기

### ISSUE THREAD

**Issue by Seokyoung-Hong** [teamSANDOL/tuk_sandol_team#17]
## 기능 상세 설명
> 학식 정보를 확인하려는 사용자의 발화에 응답하는 기능입니다.
학식 또는 학식 <식당명> 형태의 발화를 이용해 전체 또는 특정 식당의 식단을 반환합니다.

## To-do 
- Service Development
  - [x] 식당 이름으로 식당 객체 불러오기 기능 

- API 
  - [x] 식당 이름 제공 시 해당 식당 정보만 제공하는 기능
    - [x] 다른 식당 메뉴 탐색 기능 반환
  - [x]  도움말 버튼 반환 추가

- Builder
  - [x] 블록 추가 및 기본 발화 지정
  - [x] 스킬 데이터 등록
  - [x] 식당 이름 발화 등록
    -  미가: 미가, 미가식당 등
    - 수호: 수호, 수호식당 등
    - 세미콘: 세미콘, 레미콘 등
    - TIP 지하: TIP지하, TIP, 팁지, 팁지하 등
    - E동: E, E동, E동식당, 교직원식당 등

**Comment by Seokyoung-Hong** [comment]
기능을 완벽하게 구현 완료하였으므로 Issue를 종료합니다.
