### ISSUE TITLE
Cafeteria-1 학식 등록

### ISSUE THREAD

**Issue by Seokyoung-Hong** [teamSANDOL/tuk_sandol_team#18]
## 기능 상세 설명
> 식당에서 식단을 등록하는 시나리오를 처리합니다.

1. 등록 발화

2. 중식 석식 선택
    1. 중식 등록
    2. 석식 등록
 
4. 메뉴 추가
    1. 등록하실 메뉴를 작성해주세요
        1. 발화 1개당 메뉴 하나
        2. 자주 등록하는 메뉴 표시
        3. 등록 완료

5. 등록 확정
    1. 현재까지 등록된 정보
    2. 등록을 확정하시겠습니까?
        1. 예
        2. 아니요

6. 등록 완료 문구
    1. 등록이 완료되었습니다.

## To-do 
- Service Development
  - [x] id로 식당 객체 불러오기 기능
  - [x] 등록 기능
    - [x] 등록 시작(임시 파일 생성)
    - [x] 메뉴 추가
    - [x] 메뉴 삭제
    - [x] 등록 취소(임시 파일 삭제)
    - [x] 확정 기능(임시 파일 내용을 해당 식당 파일로 이동 후 임시 파일 삭제)
  - [ ] 자주 등록한 메뉴 불러오기 기능

- API 
  - [x] 중식, 석식 등록 발화 처리
    - [x] 등록 시작
    - [x] 등록
      - [x] 현재까지 등록한 메뉴 반환
      - [x] 자주 등록한 메뉴 반환
      - [x] 등록 완료 버튼 반환
      - [x] 메뉴 수정 버튼 반환
    - [x] 등록 확정
      - [x] 등록 미리보기 반환
      - [x] 등록 확정 버튼
      - [x] 등록 취소 버튼

- Builder
  - [x] 블록 추가
    - [x] 학식 등록 블록 추가 및 발화 설정
      - [x] 중식, 석식 선택 버튼 
         ↓ 아래 블록으로 연결되는 버튼

    - [x] 중식 등록 블록 추가 및 스킬 설정
    - [x] 석식 등록 블록 추가 및 스킬 설정
